# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Deployment

on:
  push:
    tags:
      - '*'
    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Build
      working-directory: ./rcaptv
      env:
        GOOS: linux
        GOARCH: amd64
        CGO_ENABLED: 0
      run: sudo go build -tags RELEASE -o ./dist/rp_tracker ./cmd/tracker

    - name: Test
      working-directory: ./rcaptv
      env:
        TEST_CLIENT_ID: ${{ secrets.TEST_CLIENT_ID }}
        TEST_CLIENT_SECRET: ${{ secrets.TEST_CLIENT_SECRET }}
        TWITCH_API_URL: https://api.twitch.tv/helix
        EVENTSUB_ENDPOINT: /eventsub
      run: go test -timeout 30s -v ./...
      
    - name: Deploy
      uses: contention/rsync-deployments@v2.0.0
      with:
        flags: -avzr --delete
        excludes: --exclude .env --exclude /.volumes/ --exclude /.git/
        user: ${{ secrets.USERNAME }}
        host: ${{ secrets.SERVER_HOST }}
        localpath: /rcaptv/
        remotepath: /staging/
        deploy_key: ${{ secrets.DEPLOY_KEY }}

    - name: Run deploy script
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: sh /build/deploy.sh
